---
title: Rockin' {{< fa brands r-project >}} with `VSCode`
author: "Marck Vaisman"
institute: "Microsoft"

execute:
  echo: true
  eval: true
  freeze: true

format:
  revealjs:
    logo: img/Microsoft-logo_rgb_c-wht.png
    theme: ['microsoft.scss']
    toc: false
    code-fold: false
    code-overflow: scroll
    code-copy: true
    scrollable: true
    pdf-separate-fragments: false
    fig-align: center
    fig-dpi: 300
    fig-width: 8
    fig-asp: 0.618
    fig-cap-location: bottom
    slide-level: 2
    slide-number: c
    margin: 0.1
    view-distance: 3
    link-external-newwindow: true
    footer: "R Gov 2023"
    smaller: true
---

# I 

## Why

- multiple languages {{< fa brands r-project >}}, {{< fa brands python >}}
- remote compute w/o having to configure server
- extensions
- 

::: notes
-   Most data professionals are typically not trained as developers/engineers but need to think like one
-   These ideas will make you a better programmer
-   Many years coding R and Python
-   Aspiring to be a better programmer
-   Interacting with large scale and distributed systems
-   Crappy code in the wild
:::

## Aargh

This is some text

::: notes
thigs that frustrate
:::

## 


## Show of hands

> -   Have you ever written an R script to be run in a non-interactive way?
> -   Did it work the first time as planned?
> -   Have you ever scheduled an R script to run without human intervention?
> -   Do you have any R script running in production?

## We're baaaack! {background-color="black" background-image="img/dancing.gif"}

## 

-   Sr.
    Cloud Solutions Architect, Microsoft

    -   6 mos as PM Azure Machine Learning

-   Adjunct Professor, Georgetown Masters of Data Science and Analytics

-   Co-Founder of DataCommunityDC

**Disclaimer:** the opinions expressed in this talk are personal and not reflective of any organization I am affiliated with.


## References

-   Plachta, Michal. *Grokking Functional Programming*, 1st ed, Manning, 2022
-   https://learn.microsoft.com/en-us/azure/architecture/example-scenario/mlops/mlops-technical-paper
-   https://daroczig.github.io/talks/
-   https://adv-r.hadley.nz/

# Thank You

marck.vaisman\@microsoft.com


